### ISSUE TITLE
[Doc] Add an example with dart

### ISSUE THREAD

**Issue by ande4485** [lslv1243/land#1]
I use Land and it generated all files from arb files.
But after how do we use L10N in dart code ?
Could you please add an example code in dart ?
Thank you

**Comment by lslv1243** [comment]
You brought up something important: there is no documentation on how to use the tool. Especially for Dart only projects. I will work on that next. But for the meantime, here is how you can use it:

You import the implementation:
```dart
import '.gen/l10n/l10n.dart';
```

And then you select the locale you want to use. Let's say you want to use English:
```dart
// the locale should be for the language the user chose or his device locale
final locale = Locale.fromSubtags(languageCode: 'en');
final l10n = L10N.locales[locale]!;
```

Having this instance of `L10N` you can access the properties/methods. For example, here is a localized string from my game:
```dart
l10n.notification_cardLevelUpReady_title; // returns "The card is ready!"
```

Remember that any locale will conform to the `L10N` interface, so you can separate the selection of the locale from the access of the properties/methods, allowing a single implementation to work on multiple locales.

---

Here is an example usage on my game server:
```dart
extension CardsNotificationFactory on NotificationFactory {
  Notification cardsReceived(
    String? senderUsername,
    String cardName,
    int amount, {
    required L10N l10n,
  }) {
    senderUsername ??= l10n.notification_cardsReceived_noUsernameSetSender;
    return Notification(
      l10n.notification_cardsReceived_title,
      l10n.notification_cardsReceived_description(
          senderUsername, amount, cardName),
    );
  }

  Notification cardLevelUpReady(
    String cardName, {
    required L10N l10n,
  }) {
    return Notification(
      l10n.notification_cardLevelUpReady_title,
      l10n.notification_cardLevelUpReady_description(cardName),
    );
  }
}
```
These accept a L10N instance (which can be of any implemented locale) and return the correct notification title and body combination.

**Comment by ande4485** [comment]
Hi,
Thank you for your answer. It's may be better to open 2 new issues but I have 2 proposals :

1. L10N would be a singleton. Why ? I use Jaspr (https://pub.dev/packages/jaspr) but I don't want to get locale for each html page and set L10N. And for dart server or other projects in dart, in the singleton, it would be a method to change the locale.
2. (optional) In your CLI, it'll be nice to set a default language and change how we can get L10N to a switch case like this ( Sorry it's not dart code, just quick example to illustrate):
getLanguage(Locale locale){
switch(locale):
Locale.fromSubtags(languageCode: 'fr'): L10NFr();
default:  L10NEn();
}

**Comment by lslv1243** [comment]
I think your first request is already supported by the underlying code but needs to be exposed through the cli, in the 'createProxyDeclaration' code. I can take a look at it on the weekend, but also feel free to create a PR if you want to.

For the second request you can easily implement it as a extension method. Unless I didn't understand it correctly.

**Comment by lslv1243** [comment]
@ande4485 I've published a new version of the CLI that allows emitting the proxy class. The changelog explains how to use it. Please let me know if that is useful to you.
